### ISSUE TITLE
OC建立的主工程 集成token-core遇到问题

### ISSUE THREAD

**Issue by zmubai** [consenlabs/token-core-ios#11]
OC建立的主工程使用cocoapod导入#import "TokenCore-Swift.h"文件中的CoreBitcoin module无法找到。

系统生成的中间文件TokenCore-Swift.h中 有@import CoreBitcoin . 但编译起来提示module not fuound.目前还没找到解决办法。

**Comment by XuNeal** [comment]
目前我们还并未在OC环境下测试过，回来我测试一下，顺便问一下您的项目本身是否引用过CoreBitcoin的库。另外你目前是用的是什么编译环境。请帖一下你的Xcode版本号以及mac版本号

**Comment by XuNeal** [comment]
Duplicate of #12

**Comment by zmubai** [comment]
> 目前我们还并未在OC环境下测试过，回来我测试一下，顺便问一下您的项目本身是否引用过CoreBitcoin的库。另外你目前是用的是什么编译环境。请帖一下你的Xcode版本号以及mac版本号

re:主工程没引用过CoreBitcoin。mac版本10.13.6 (17G65),xcode Version 10.0 (10A255)。不过在主工程创建swift,swift里面improt tokenCore就可以。

**Comment by culturetown** [comment]
OC环境下编译 TokenCore-Swift.h 里import CoreBitcoin 报错，提示Module ‘CoreBitcoin’ not found

**Comment by XuNeal** [comment]
如果你这问题已解决那我就先关闭了

**Comment by zmubai** [comment]
thanks




| |
曾柏亮
邮箱：zengbailiang@126.com
|

签名由 网易邮箱大师 定制

在2018年11月08日 10:38，Neal Xu 写道：

如果你这问题已解决那我就先关闭了

**Comment by yaorenjin1986** [comment]
我是OC项目，按照上述方式处理，还是不可以啊。
