### ISSUE TITLE
大佬，我打不开项目，pod install不管用啊

### ISSUE THREAD

**Issue by 794117540** [consenlabs/token-core-ios#17]

**Comment by zhen6939** [comment]
请提供更多的报错信息

**Comment by 794117540** [comment]
大佬，我能问一下，这个项目是IMtoken源码吗

**Comment by XuNeal** [comment]
这个项目主要包括imToken使用的钱包管理和签名相关代码，不包括整个App的代码。
目前这个代码只包含一个库程序，示例代码我们正在编写中

**Comment by XuNeal** [comment]
如果没有更多问题我先关闭该issue了。有后续问题你可以随时再打开
