### ISSUE TITLE
let dustThreshold: Int64 = 2730 这个值是固定的？还是可以根据自己的需求改动？

### ISSUE THREAD

**Issue by AlleniCode** [consenlabs/token-core-ios#18]
在 BTCTransactionSigner.swift 文件中，第 60 行 【let dustThreshold: Int64 = 2730】，
这个值是固定的？还是可以根据自己的需求改动？谢谢！

**Comment by kaichen** [comment]
这个实际上在一定时间内是由矿工集体共识得到，相对稳定。

如果你需要加入自己的 dust 逻辑最好在前端传入时，阻止你认为的 dust 大小 utxo 进入签名过程。

ref https://bitcoin.stackexchange.com/questions/10986/what-is-meant-by-bitcoin-dust
