### ISSUE TITLE
cocoapods error

### ISSUE THREAD

**Issue by MFJun** [consenlabs/token-core-ios#2]
Analyzing dependencies  
Pre-downloading: `TokenCore` from `git@github.com:consenlabs/token-core-ios.git`, branch `master`  
  
[!] Error installing TokenCore  
[!] Failed to download 'TokenCore'.  
  
pod search TokenCore  
[!] Unable to find a pod with name, author, summary, or description matching `TokenCore`

**Comment by XuNeal** [comment]
@MFJun can you retry now? maybe we are push deploying to the pod. below is the result when run the `pod search TokenCore` in my computer

 pod search TokenCore
![image](https://user-images.githubusercontent.com/10441775/47405182-eefbcd80-d782-11e8-84e2-33a3ea3e960a.png)

**Comment by MFJun** [comment]
@XuNeal thanks
