### ISSUE TITLE
OC环境下 pod 后编译的问题

### ISSUE THREAD

**Issue by culturetown** [consenlabs/token-core-ios#20]
OC环境下编译 TokenCore-Swift.h 里import CoreBitcoin 报错，提示Module ‘CoreBitcoin’ not found，有好的解决方法吗？

**Comment by NahtanLi** [comment]
新建swift文件，在这个swift文件中 import TokenCore 就可以了

**Comment by XuNeal** [comment]
Duplicate of #11
