### ISSUE TITLE
根据私钥导入身份

### ISSUE THREAD

**Issue by limengCode** [consenlabs/token-core-ios#21]
请问怎么根据私钥导入身份？

**Comment by kaichen** [comment]
身份是用来推导多个私钥的，所以无法反向操作，身份只能从助记词导入。

**Comment by XuNeal** [comment]
如果你想用这个私钥钱包，你可以创建一个心身份然后导入你这个私钥钱包。这样你的私钥钱包就可以正常使用了

**Comment by XuNeal** [comment]
该问题已经很长时间没回复过了我先关闭了，如果你有后续问题欢迎随时打开

**Comment by wkn66** [comment]
> 如果你想用这个私钥钱包，你可以创建一个心身份然后导入你这个私钥钱包。这样你的私钥钱包就可以正常使用了

您好 ，请问能贴下代码么？
