### ISSUE TITLE
How to get the wallet's balance ?

### ISSUE THREAD

**Issue by hcsaaron** [consenlabs/token-core-ios#22]
Is the core has network request? I can not find.

**Comment by xwartz** [comment]
No, TokenCore provides the API that allows you to manage your wallets and sign transactions in BTC, ETH and EOS chains.

Duplicate of #15

**Comment by haizhiwen** [comment]
我没有找到关于获取钱包余额的参数，请告知如何获取钱包余额

**Comment by kaichen** [comment]
> 我没有找到关于获取钱包余额的参数，请告知如何获取钱包余额

This is probably what you want, [https://github.com/BANKEX/web3swift].

**Comment by haizhiwen** [comment]
web3swift 需要pod BigInt ~> 3.1 版本，而你这个是  BigInt 3.0.0 版本，我cocopods 失败，这两个冲突应该怎么解决

**Comment by hcsaaron** [comment]
> web3swift 需要pod BigInt ~> 3.1 版本，而你这个是 BigInt 3.0.0 版本，我cocopods 失败，这两个冲突应该怎么解决

我和你遇到的问题一样，不知道如何解决冲突
