### ISSUE TITLE
Why the ETC keystore "address" is not  support "0x....." but "......"

### ISSUE THREAD

**Issue by Li-Qun** [consenlabs/token-core-ios#24]
Why the ETC keystore "address" is not  "0x....." but "......"
if other app keystore 's "address" is "0x...."  the wallet is nil
but the imtoken app is support all above types.

Please think twice and weather need to update the sdk. Or tell me ,what should I do if the user use keystore with address "0x...."
eg:

> let json = "{\"address\":\"0xc9cbc3bcef3b50d765a1527d9a63a6c9eda7e7bd\",\"id\":\"e2ef2600-8928-4264-a3e9-e2129584e995\",\"version\":3,\"crypto\":{\"cipher\":\"aes-128-ctr\",\"ciphertext\":\"3d4c5e461b05bd3be1719c1c420c66390307bd7997204e5d41aa7c9c8b0b6d6d\",\"cipherparams\":{\"iv\":\"8621503dbc68031b79dd28289b93c1b1\"},\"kdf\":\"scrypt\",\"kdfparams\":{\"dklen\":32,\"n\":4096,\"p\":6,\"r\":8,\"salt\":\"26552d24acb8ea32aa35827d1cce999458eed744750ccc81c00055b2c2dfc793\"},\"mac\":\"4148aeb208e6ce123eacd8b5cdbfe45cdaafe69c3c821ceb2ca7a99de31f4282\"}}"//TestHelper.loadJSON(filename: "v3-scrypt-testpassword")
>     let password = "q"
> 
>     do {
>       let keystore = try json.tk_toJSON()
>       let meta = WalletMeta(chain: .eth, source: .keystore)
>       let wallet = try WalletManager.importFromKeystore(keystore, encryptedBy: password, metadata: meta)
> }
//the wallet is nil  because of "0xc9cbc3bcef3b50d765a1527d9a63a6c9eda7e7bd"
>

**Comment by Li-Qun** [comment]
And  use the clone TokenCore  can use the func WalletManager.importFromKeystore, but when I pod the sdk into my project ,  the func WalletManager.importFromKeystore doesn't work ! 
Then debug  and find the difference:


> public static var currentIdentity: Identity? {
>     set(newIdentity) {
>       _currentIdentity = newIdentity //the clone one can execute this code
>     }
>     get {
>       if _currentIdentity == nil {
>         _currentIdentity = storage.tryLoadIdentity() //but the sdk pod into my project execute this code
>       }
>       return _currentIdentity
>     }
>   }

pleae tell me  what should I do to solve that problem ??

**Comment by Li-Qun** [comment]
And  use the clone TokenCore  can use the func WalletManager.importFromKeystore, but when I pod the sdk into my project ,  the func WalletManager.importFromKeystore doesn't work ! 
Then debug  and find the difference:


> public static var currentIdentity: Identity? {
>     set(newIdentity) {
>       _currentIdentity = newIdentity //the clone one can execute this code
>     }
>     get {
>       if _currentIdentity == nil {
>         _currentIdentity = storage.tryLoadIdentity() //but the sdk pod into my project execute this code
>       }
>       return _currentIdentity
>     }
>   }

please tell me  what should I do to solve that problem ??

**Comment by XuNeal** [comment]
Hey @Li-Qun 
1. TokenCore is follow the V3 Keystore format, the keystore standard of Ethereum, which the address is not start with '0x'.
2. We have do the full test on ETC.
3. We are working on you third question

**Comment by Li-Qun** [comment]
@ XuNeal   小哥哥 我知道我们都会说汉语了，“ETH 不是ETC。。。。。”
1.针对你回答的第一个问题，没有解决我的问题，在clone 的sdk 项目里, 如果keystore 中带了 0x开头的地址，sdk 是不识别的,我该怎么处理这个问题呢???
重点是imtoken app 中经过测试，imtoken 自己生成的keystore 是不带0x的，但是导入是带0x开头也可以正常交易，并且再查看keystore时候也是带0x开头的，为啥这个TokenCore  当且仅当不带0x开头才行 是吗？否者 导入的wallt 就是nil（难道要我识别一下用户导入的keystore...转换一下。。。这是我当前能想到的方法并且十分土。。。）
2.做了全面测测试？ ETC ？？？===》ETH
3.Pod 下来的sdk方法不能像clone 项目中那样正常使用，期待你们的解决谢谢。waiting 至此，使用你们的SDK进度完全停滞，期待你们能解决这个问题。

**Comment by XuNeal** [comment]
该问题已经长时间没有回复，我先关掉了
