### ISSUE TITLE
How to create a eos transfer transaction?

### ISSUE THREAD

**Issue by limengCode** [consenlabs/token-core-ios#26]
I know that I can use 'eosSignTransaction',but how to set the parameter of [EOSTransaction]? The 'Hex tx data', what is the data meaning？

**Comment by XuNeal** [comment]
@xwartz  Pls show some examples. thanks

**Comment by xwartz** [comment]
Hello, @limengCode
You can get the hex tx data from the following method:

```ts
export const getTxHex = async (actions: <{name: string,
  account: string,
  data: object,
  authorization?: { actor: string, permission: string }[],}>[]): Promise<{ txHex: string, tr: object }> => {
  const { transaction } = await Eos().transaction({ actions }, {
    sign: false,
    broadcast: false,
  })

  const txHex = transaction.buf.toString('hex')
  const tr = transaction.transaction

  return {
    txHex,
    tr,
  }
}
```

If you want to know more details, you should read EOSJS source code:

https://github.com/consenlabs/eosjs/blob/a0d0dc7e571079a74b1ee6005d763a46f0bc309d/src/write-api.js#L413-L558

**Comment by limengCode** [comment]
thanks

**Comment by XuNeal** [comment]
@limengCode 
This issue is inactive for long time, I will close it, you can reopen it if come more question.
