### ISSUE TITLE
钱包操作报 walletNotFound

### ISSUE THREAD

**Issue by YoungCao1** [consenlabs/token-core-ios#27]
创建多个钱包，只生成一个identity.json文件？创建多个钱包后，做钱包导出操作，只有最新创建的那个钱包可以导出成功，之前的钱包都报 walletNotFound ， 这是什么情况？

**Comment by kaichen** [comment]
请给出出问题的代码片段，只是简单的现象描述无法得到正确判断，谢谢。

**Comment by huchengjian** [comment]
> 请给出出问题的代码片段，只是简单的现象描述无法得到正确判断，谢谢。

照们现在的理解只支持创建一个identity身份(新创建的identity会替换旧的), 这是什么样的考虑?

**Comment by XuNeal** [comment]
这个属于纯产品角度考虑的，imToken主要是2C的产品，其产品逻辑你可以用一个助记词管理多个链上的钱包。所以我们目前只支持创建一个助记词。但是你可以通过导入的方式管理你已有的钱包

**Comment by XuNeal** [comment]
该问题长时间未回复，我先暂时关掉了

**Comment by wkn66** [comment]
> 这个属于纯产品角度考虑的，imToken主要是2C的产品，其产品逻辑你可以用一个助记词管理多个链上的钱包。所以我们目前只支持创建一个助记词。但是你可以通过导入的方式管理你已有的钱包。
> 如果你有需要创建多个钱包的需求可以参见其createIdentity的代码。单独做一些修改来满足你的业务逻辑

嗨，您好，我觉得您可以出个添加钱包的功能进行展示一下，处理下walletnotfound，我想应该有很多人有这种需求
