### ISSUE TITLE
How to export BTC privateKey? 

### ISSUE THREAD

**Issue by hcsaaron** [consenlabs/token-core-ios#28]
How to export BTC privateKey? 
I try the method from WalletManager 
exportPrivateKey(walletID: String, password: String) throws -> String 
but the value is not a BTC privateKey

**Comment by culturetown** [comment]
I had the same problem ,  getting a long string of characters

**Comment by XuNeal** [comment]
We create the Hierarchical Deterministic BTC wallet in TokenCore. It use a seed and BIP path to derived the infinite privateKeys.  If you export one PK of it, you will lose the money on other PKs. So we  forbid export the pirvateKey on the HD Wallet, instead you can export the mnemonic (the seed in a human readable format).

But if you have a random pk of btc wallet, you can import it by `importWalletFromPrivateKey` and export by `exportPrivateKey`.

**Comment by XuNeal** [comment]
Hey the thread has not update for a long time, I will close it. Pls reopen it when you need again
