### ISSUE TITLE
How do I use the private key to derive the public key？

### ISSUE THREAD

**Issue by limengCode** [consenlabs/token-core-ios#29]
I know this "let basicWallet = [try WalletManager.importFromPrivateKey(privateString as String, encryptedBy: password as String, metadata: metadata, accountName: address as String)]"
but this methods need an address.How can I get the publicKey without address,just with privateKey?

**Comment by XuNeal** [comment]
@limengCode param of accountName is used for EOS wallet, if you'r importing ether wallet. you can call the other method `try WalletManager.importFromPrivateKey(privateString as String, encryptedBy: password as String, metadata: metadata)`

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
