### ISSUE TITLE
大佬们,  ETH钱包, 如何进行ERC20代币交易啊

### ISSUE THREAD

**Issue by Kingzhijie** [consenlabs/token-core-ios#30]
let signResult = WalletManager.ethSignTransaction(
        walletID: String,
        nonce: String,
        gasPrice: String,
        gasLimit: String,
        to: String,
        value: String,
        data: String,
        password: String,
        chainID: Int
      )

这个api是 eth交易的吧,  代币ERC20如何写交易啊

**Comment by Li-Qun** [comment]
同问，代币合约地址吗 往哪里添？并且没看到单元测试中有关于ETH和其代币的例子

**Comment by ashchan** [comment]
ERC20交易，`to` 填 contract 地址，`data` 填 `transfer` 方法的实际数据。

**Comment by Kingzhijie** [comment]
有具体的操作示例吗,还是不太明白怎么操作, 望进一步告知 😄谢谢

**Comment by Kingzhijie** [comment]
> ERC20交易，`to` 填 contract 地址，`data` 填 `transfer` 方法的实际数据。

有具体的操作示例吗,还是不太明白怎么操作, 望进一步告知 😄谢谢

**Comment by ashchan** [comment]
这个需要了解 ABI 等，可以参考一下这个 SO 问答：https://ethereum.stackexchange.com/questions/24828/how-to-send-erc20-token-using-web3-api

虽然 token-core 本身不提供合约解析功能，但 `data` 其实可以硬编码为 ERC20 的  `transfer` 方法的 hash 值（`0xa9059cbb`）加上参数值（接收地址和金额 wei）的 hex （要补零）。请搜索一下相关文档查询。
