### ISSUE TITLE
About EOS transfer

### ISSUE THREAD

**Issue by limengCode** [consenlabs/token-core-ios#31]
public static func eosSignTransaction(
    walletID: String,
    txs: [EOSTransaction],
    password: String
    ) throws -> [EOSSignResult] {
    guard let wallet = Identity.currentIdentity?.findWalletByWalletID(walletID) else {
      throw GenericError.walletNotFound
    }
What is the use of this method? Is it just for signatures？Or I can use it to transfer money？

**Comment by XuNeal** [comment]
Used for sign any message, include transfer, vote etc. you can use the eosjs to serial the content to sign.

**Comment by XuNeal** [comment]
I will close this issue, reopen it when you have any update
