### ISSUE TITLE
创建 `Identity ` 耗时问题

### ISSUE THREAD

**Issue by linKnowEasy** [consenlabs/token-core-ios#32]
![image](https://user-images.githubusercontent.com/8413135/48243041-23c18300-e419-11e8-9a64-a504c4f3e432.png)
![image](https://user-images.githubusercontent.com/8413135/48243053-38058000-e419-11e8-987f-fdf4f9b9a7f9.png)

现象:  在 `AppleDelegate` 测试了一下耗时. 创建一个 `Identity` 耗时 `12 秒`左右。 
环境: `Xcode 10.1` ,  `真机 iPhone 7. 12.0.1 系统`,
引用方式:  clone 工程后. 修改了`PodFile`  `pod "CryptoSwift", "0.10.0"`  , 编译后工程引用 `TokenCore` 动态库

疑惑的是. 运行测试用例时候, 创建耗时大概 `0.5 秒`
期待您的回复

**Comment by ashchan** [comment]
测试用例用了较小的参数以加快运行速度。
Release 模式会快一些。Identity 创建时要生成三种不同的钱包，iPhone 7上10秒上下，大致属于可接受范围。或者可以象测试案例一下，修改参数：

https://github.com/consenlabs/token-core-ios/blob/master/Tests/TestCase.swift#L50

**Comment by linKnowEasy** [comment]
@ashchan  方便的话. 能问下
```
EOSTransaction(
        data: "c578065b93aec6a7c811000000000100a6823403ea3055000000572d3ccdcd01000000602a48b37400000000a8ed323225000000602a48b374208410425c95b1ca80969800000000000453595300000000046d656d6f00",
        publicKeys: ["EOS5SxZMjhKiXsmjxac8HBx56wWdZV1sCLZESh3ys1rzbMn4FUumU"],
        chainID: TestData.eosChainID
      )
```
中 `data` 是怎么生成的嘛, 看了 `eosjs` 的源码. 好像是一个结构体, 调用了 fcbuffer 的方法. 得到一个 16进制字符串.
我想问下. iOS 的操作是不是 `transaction `  `json` 字典直接转 字符串 . 然后 调用 `tk_toHexString` 方法.生成16进制数据.  得到的结果就是所需要的 `data`

**Comment by ashchan** [comment]
@linKnowEasy 这部分我不是太了解，token-core 部分没有做处理。请 @XuNeal 看看该怎么构建 data。

**Comment by simondaigogogo** [comment]
> @ashchan 方便的话. 能问下
> 
> ```
> EOSTransaction(
>         data: "c578065b93aec6a7c811000000000100a6823403ea3055000000572d3ccdcd01000000602a48b37400000000a8ed323225000000602a48b374208410425c95b1ca80969800000000000453595300000000046d656d6f00",
>         publicKeys: ["EOS5SxZMjhKiXsmjxac8HBx56wWdZV1sCLZESh3ys1rzbMn4FUumU"],
>         chainID: TestData.eosChainID
>       )
> ```
> 中 `data` 是怎么生成的嘛, 看了 `eosjs` 的源码. 好像是一个结构体, 调用了 fcbuffer 的方法. 得到一个 16进制字符串.
> 我想问下. iOS 的操作是不是 `transaction ` `json` 字典直接转 字符串 . 然后 调用 `tk_toHexString` 方法.生成16进制数据. 得到的结果就是所需要的 `data`

请问下，后面这个问题你有研究出结果吗？

**Comment by linKnowEasy** [comment]
@simondaigogogo 
https://blog.csdn.net/akai9898/article/details/83447788
参考这个系列
其实是把交易数据发到链上. 进行序列化. 打包
过去的有点久了. 只能帮到这里了
