### ISSUE TITLE
大佬，转账的data用js，门槛设的是不是有点高了？

### ISSUE THREAD

**Issue by limengCode** [consenlabs/token-core-ios#34]
大佬，转账的data用js，门槛设的是不是有点高了？

**Comment by XuNeal** [comment]
data用js不太明白什么意思？如果你是想问关于ERC20代币转账的问题可以参见
https://github.com/consenlabs/token-core-ios/issues/25

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
