### ISSUE TITLE
iOS怎么修改钱包密码？Android有修改钱包密码的方法，为什么iOS的没有？

### ISSUE THREAD

**Issue by hcsaaron** [consenlabs/token-core-ios#37]
iOS怎么修改钱包密码？Android有修改钱包密码的方法，为什么iOS的没有？

**Comment by hcsaaron** [comment]
> 钱包密码只是用来加密本地keystore的密码，并不是链上密码。你可以使用同一个私钥或者助记词重新导入设置不同的密码即可。

非常感谢！再请教一下如何修改名称？我没发现有修改名称的api，难道要和修改密码一样重新导入吗？导入需要密码，不可能因为修改名称而让用户输入密码吧

**Comment by XuNeal** [comment]
实在抱歉，暂时确实未提供这个功能。欢迎提交PR，我也会给产品反应这个问题
