### ISSUE TITLE
初始化时如何通过keystone、私钥去恢复钱包？

### ISSUE THREAD

**Issue by luanlzsn** [consenlabs/token-core-ios#39]
Identity只能创建钱包和通过助记词恢复钱包，那如果通过keystone、私钥恢复钱包了？
通过WalletManager导入的话，会报IdentityError.invalidIdentity错误

**Comment by XuNeal** [comment]
目前token-core会和identity绑定到一起，如果你只是想用私钥或者keystore，你可以完全新建一个identity，然后再讲你的keystore和私钥导入。后续导入的钱包不会喝identity有任何关系。

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
