### ISSUE TITLE
No such module 'CommonCrypto'

### ISSUE THREAD

**Issue by IChengLiWei** [consenlabs/token-core-ios#4]
i install the sdk ,but there is a issues confused me . No such module 'CommonCrypto' inMnemonic.swift

**Comment by ashchan** [comment]
Are you running macOS 10.14 Mojave? If so please refer to the [Troubleshooting](https://github.com/consenlabs/token-core-ios#troubleshooting) section in README.

**Comment by defchain** [comment]
I'm running in macos 10.13.2,I have the same issue.

**Comment by eggacher** [comment]
@ashchan I have the same issue in MacOS 10.13.2

**Comment by ashchan** [comment]
Check if installing Xcode command line tools solves the issue:

```shell
xcode-select install
```

**Comment by eggacher** [comment]
@IChengLiWei @ashchan 
I have resolve the issue;

In Modules/module.modulemap 

```
/// On macOS 10.14 and above, install /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
/// to have /usr/include headers.
module CCommonCrypto {
  header "/usr/include/CommonCrypto/CommonCrypto.h"
  export *
}
```

in Mnemonic.swift
the header is:
```
import Foundation
import CommonCrypto
```

change the header with 
```
import Foundation
import CCommonCrypto
```

**Comment by ashchan** [comment]
Interesting. @XuNeal might want to have a look and double check this.

**Comment by XuNeal** [comment]
I will take a look, by now, we use CCommonCrypto in Xcode9, CommonCrypto in Xcode10.

**Comment by ashchan** [comment]
@XuNeal I do find that with Xcode 10, `CommonCrypto` could be referenced even the headers are not present user `/usr/include`. Do you have any documents/articles regarding this difference?

**Comment by XuNeal** [comment]
@ashchan It seems the Xcode10 has provide the `CommonCrypto` as a swift framework, we do not need to wrap it as a module. you can check https://stackoverflow.com/questions/25248598/importing-commoncrypto-in-a-swift-framework

**Comment by ashchan** [comment]
@XuNeal Wonderful! Thanks a lot.
