### ISSUE TITLE
BTC找零地址为什么不是钱包本身的地址？

### ISSUE THREAD

**Issue by hcsaaron** [consenlabs/token-core-ios#40]
WalletManager.swift里面，代码如下：
let changeAddress = changeKey.address(on: isTestnet ? .testnet : .mainnet, segWit: segWit)

我打印出来changeAddress是一个奇怪的地址，找零的钱都不见了？
为什么changeAddress不直接用 wallet.address?

**Comment by XuNeal** [comment]
这个属于BTC确定性钱包的产品设计。每次更换一个推导出来的新钱包收款地址可以增加你本人的匿名性。并且这个找零的钱也并未丢失，你还是可以用你的助记词推导出你的任意找零地址，并且解锁花掉这笔钱。
详细内容请参见http://book.8btc.com/books/6/masterbitcoin2cn/_book/ch05.html 一节

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
