### ISSUE TITLE
验证密码为什么ios要花5秒钟，安卓速度很快

### ISSUE THREAD

**Issue by jianrenWu** [consenlabs/token-core-ios#42]

**Comment by XuNeal** [comment]
在加密私钥的过程中，Android使用了PBKDF n=10240.而iOS使用了SCrypt 26W次的迭代运行。简单来说就是Android的设备普遍配置较低。我们相应的降低了一下安全系数。iOS本身没有这个问题我们所以我们安全系数就采用的比较高。

Android中一次解密校验需要122ms左右。如果你的密码是一个8位密码，黑客试出你的密码需要 8位^60(a-zA-Z加部分常见字符) * 122ms / 1000 / 60 / 60 / 24 / 365 = 5.928604e+45 年。所以Android的部分也能接受。

但是安全无绝对，如果你的密码是比较常见的组合或者和你名字有关系之类的。可能黑客尝试几千次就能试出来。所以iOS在用户可容忍的情况下算法做的复杂一些也是有好处的。

**Comment by linKnowEasy** [comment]
@jianrenWu 
可以通过设置 Crypto.ScryptKdfparams.defaultN = 1024 来加快速度, 这样会牺牲安全性
注意  Crypto.ScryptKdfparams.defaultN  的值好像只能是 1024 和 1024 * 256 , 设置其他值会导致加解密失效, 具体原因我没有深入研究

**Comment by XuNeal** [comment]
如没其他问题我先关闭改issue了。如果你有后续问题可以重新打开
