### ISSUE TITLE
为什么只能验证ETH地址的有效性，没找到验证BTC地址的有效性？

### ISSUE THREAD

**Issue by hcsaaron** [consenlabs/token-core-ios#47]
AddressValidator这个类可以验证ETH地址的有效性，但是找来找去都没找到可以验证BTC地址的有效性？可以提供相应的方法吗

**Comment by XuNeal** [comment]
BTC相关验证可以参见https://github.com/consenlabs/token-core-ios/blob/master/Vendor/CoreBitcoin/BTCAddress.m#L49

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
