### ISSUE TITLE
怎么生成助记词会出现两个(多个)相同的单词？？？

### ISSUE THREAD

**Issue by hcsaaron** [consenlabs/token-core-ios#50]
我使用 MnemonicUtil.generateMnemonic() 生成助记词，里面可能会包含两个(多个)相同的助记词，导致备份助记词时出问题。这个怎么解决？

**Comment by ashchan** [comment]
BIP39 并没有规定说一个单词只能出现一次。所以这是有一定机率发生的。如果备份时有问题，说明备份逻辑存在 bug 或缺陷。

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
