### ISSUE TITLE
关于比特币转账

### ISSUE THREAD

**Issue by iOScc** [consenlabs/token-core-ios#51]
public static func btcSignTransaction(
    walletID: String,
    to: String,
    amount: Int64,
    fee: Int64,
    password: String,
    outputs: [[String: Any]],
    changeIdx: Int,
    isTestnet: Bool,
    segWit: SegWit
  ) throws -> TransactionSignedResult

您好,转账时参数outpus是传以下的数组吗 outputs   
    NSError* error = nil;
    NSArray* outputs = [[[BTCBlockchainInfo alloc] init] unspentOutputsWithAddresses:@[ [BTCAddress addressWithString:@"1FRVQUbzFSYB6VPdz1KowbDog7v679pojT"] ] error:&error];

但是好像不对,另外changeIdx也不知如何生成,麻烦坐着可否提供个简单的 demo呢 谢谢

**Comment by iOScc** [comment]
作者

**Comment by XuNeal** [comment]
```
let utxos = [
      [
        "txHash": "02d8595fc5d4adc5e06c73f44e39fe86c7f0a516b7d4e0d37b9e1e83c93596a5",
        "vout": 1,
        "amount": "29719880",
        "address": "n2ZNV88uQbede7C5M5jzi6SyG4GVuPpng6",
        "scriptPubKey": "76a914e6cfaab9a59ba187f0a45db0b169c21bb48f09b388ac"
      ],
      [
        "txHash": "02d8595fc5d4adc5e06c73f44e39fe86c7f0a516b7d4e0d37b9e1e83c93596a5",
        "vout": 2,
        "amount": "1",
        "address": "n2ZNV88uQbede7C5M5jzi6SyG4GVuPpng6",
        "scriptPubKey": "76a914e6cfaab9a59ba187f0a45db0b169c21bb48f09b388ac"
      ]
    ].map { UTXO(raw: $0)! }
```
UTXO的结构如上所示

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
