### ISSUE TITLE
如何将找零地址, 设置成自己的钱包地址呢? 

### ISSUE THREAD

**Issue by 453548460Anders** [consenlabs/token-core-ios#52]
急急急急!!! 如何将找零地址, 设置成自己的钱包地址呢?

**Comment by XuNeal** [comment]
在token-core中目前支持两种形式的钱包
普通的WIF钱包，改钱包地找零地址就是转账地址
HD钱包：HD钱包使用的BIP44地规范，会根据你的助记词在每笔转账时自动计算一个新的地址，但是你同样对该地址有掌控权，你也可以花费在改地址上的Bitcoin。简单来说你不用关心找零地址的管理

如果你真的想要写死一个找零地址需要你自己fork代码并加入相关API即可

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem

**Comment by 386401813** [comment]
@XuNeal 请问有哪些钱包是WIF钱包呢？imtonken是否可以将找零地址设置为转账地址呢？（目前测试是不可以，但是网上说似乎有技术手段可以实现）

感谢大神！
