### ISSUE TITLE
助记词创建EOS

### ISSUE THREAD

**Issue by My-Old-Driver** [consenlabs/token-core-ios#6]
如何使用助记词创建EOS的私钥呢

**Comment by beenhero** [comment]
看一下 Identity.swift#func deriveWallets(for chainTypes: [ChainType], mnemonic: String, password: String) throws -> [BasicWallet] {...}

**Comment by My-Old-Driver** [comment]
我通过这种方式获取到了eos的KeyPair得到了公私钥信息
```
let basicWallet = try identity.deriveWallets(for: [.eos], password: "")
let eos = try basicWallet.first?.privateKeys(password: "")
print(eos?.first)
```
但是我不知道使用哪个方法可以获取到BTC和ETH的公钥，需要自己去扩展实现将私钥转换成公钥的方法吗？
```
let ethereumWallet = identity.wallets[0]
let bitcoinWalelt = identity.wallets[1]

let ethPrv = try ethereumWallet.privateKey(password: "")
let btcPrv =  try bitcoinWalelt.privateKey(password: "")
```

**Comment by XuNeal** [comment]
@My-Old-Driver 
BTC和ETH的公钥都可以是用 `BTCKey(privateKey: Data())?.publicKey`需要导入`CoreBitcoin`
另外请问你什么时候需要公钥呢？因为如果需要计算地址的话一般返回的信息都提供了的。

SegWit确实要声明为Public，晚点我们改一下

**Comment by XuNeal** [comment]
@My-Old-Driver Hey if you do not have any more question, I will close the issue now. You can reopen it at any time when you meet some question
