### ISSUE TITLE
compile error with token-core-ios

### ISSUE THREAD

**Issue by mousehaohao** [consenlabs/token-core-ios#60]
Hi Team,
    There are some issues when I compile with token-core-ios, here's the error information:
    Use of unresolved identifier 'CBC'
    Use of unresolved identifier 'CTR'
    It may be related with the library CryptoSwift, could you please help to figure out how to solve this? 
    Thanks.

**Comment by mousehaohao** [comment]
I've fixed this issue when i found the PR, maybe it's a typo?

**Comment by zhengyanfeng** [comment]
> I've fixed this issue when i found the PR, maybe it's a typo?

how did you fixed this

**Comment by zhengyanfeng** [comment]
> I've fixed this issue when i found the PR, maybe it's a typo?
what is "found the PR"?

**Comment by euforic** [comment]
Should be fixed with #59

**Comment by XuNeal** [comment]
@euforic Thanks, It has merged

**Comment by likuiliang** [comment]
在前面添加一个 .  就OK了
.CBC
.CTR

**Comment by zhengyanfeng** [comment]
> @euforic Thanks, It has merged

nice,thanks

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
