### ISSUE TITLE
Pod update 报错

### ISSUE THREAD

**Issue by likuiliang** [consenlabs/token-core-ios#68]
bogon:Example likuiliang-Answer$ pod install
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/executable.rb:89: warning: Insecure world writable dir /Users/answer/Documents/flutter/bin in PATH, mode 040777
Analyzing dependencies
Pre-downloading: TokenCore from https://github.com/consenlabs/token-core-ios.git

[!] Unable to find a specification for TokenCoreDep depended upon by TokenCore

**Comment by likuiliang** [comment]
如此解决：pod 'TokenCore', :git=> 'https://github.com/consenlabs/token-core-ios.git',:commit=>'03817d489a42d882ccffae45468e4199f807dc06'

**Comment by renyuanhao** [comment]
这个问题我这边用pod 'TokenCore', :git=> 'https://github.com/consenlabs/token-core-ios.git',:commit=>'03817d489a42d882ccffae45468e4199f807dc06'还是不行啊

**Comment by renyuanhao** [comment]
不知道你这个问题怎么解决的
