### ISSUE TITLE
想在项目里面集成，可是引用找不到

### ISSUE THREAD

**Issue by Merlini93** [consenlabs/token-core-ios#81]
将下载的tokencore文件夹里面的文件拖到项目中，编译报错No such module 'CoreBitcoin.libscrypt'和No such module 'secp256k1',然后直接在tokencore中编译也报这个错，好像Modules里面的module.modulemap没有起作用，都找不到头文件。

Xcode:10.3 
Mac OS:10.14.6 
Podfile就是tokencore自带的没有改动

请问如何将项目集成到swift项目中呢？

**Comment by Merlini93** [comment]
![image](https://user-images.githubusercontent.com/11328707/62674225-1e0ec300-b9d4-11e9-8bf0-873a29447a37.png)

**Comment by wangzhilongh** [comment]
我也遇到这个错了？你解决了吗？怎么解决的，求教，谢谢！

**Comment by Merlini93** [comment]
你加我qq了吗？这个问题我没解决，我换成swift项目用cocoapods集成了

**Comment by ciyaer** [comment]
> 你加我qq了吗？这个问题我没解决，我换成swift项目用cocoapods集成了

@Merlini93 你解决了吗？QQ多少？
