### ISSUE TITLE
BTC 钱包导出的私钥不正确

### ISSUE THREAD

**Issue by wq19920109** [consenlabs/token-core-ios#82]
通过助记词导入或者新创建的BTC钱包，导出的私钥格式不正确，请问是我创建的有什么问题么

var metadata = WalletMeta(source: .newIdentity)
metadata.network = Network.mainnet
let (mnemonic, identity) = try Identity.createIdentity(password: pwd, metadata: metadata                let bitcoinWalelt = identity.wallets[1]

var metadata1 = WalletMeta(source: .mnemonic)
        metadata1.network = Network.mainnet
        metadata1.chain = .btc
let wallet = try WalletManager.importFromMnemonic(mnemonic, metadata: metadata1, encryptBy: password, at: BIP44.btcTestnet)

**Comment by VVanaheim** [comment]
用优盾钱包试试，支持多币种，用到现在也没发现什么bug

**Comment by XuNeal** [comment]
导出私钥格式不正确是指？能否提供一些测试数据对比一下看看呢？
造成这个问题可能存在的原因是，导入和导出的网络不一致，path，或者私钥是否是压缩或者非压缩格式
