### ISSUE TITLE
master   branch pod install error

### ISSUE THREAD

**Issue by jh235** [consenlabs/token-core-ios#84]
pod 'TokenCore', :git=> 'https://github.com/consenlabs/token-core-ios.git',branch: 'master'

[!] The 'Pods-Wallet' target has transitive dependencies that include statically linked binaries: (/Users/jiang/Desktop/Wallet/Pods/OpenSSL-Universal/lib-ios/libcrypto.a and /Users/jiang/Desktop/Wallet/Pods/OpenSSL-Universal/lib-ios/libssl.a)

Xcode 10.3 (10G8)
pod  version 1.7.1

**Comment by jh235** [comment]
pod  version 1.7.1

**Comment by XuNeal** [comment]
Please check this https://github.com/CocoaPods/CocoaPods/issues/7234
